name: Validate bundle CSV

on:
  pull_request:
    branches:
    - main
    - 'release-*.*.*'
    paths:
    - 'bundle/**'
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Validate bundle
        run: make bundle
